/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from 'react'

export const Index: Record<string, any> = {
  utils: {
    name: 'utils',
    description: '',
    type: 'registry:lib',
    files: [{
      path: 'src/registry/src/lib/utils.ts',
      type: 'registry:lib',
    }],
  },
  'sticker-animation': {
    name: 'sticker-animation',
    description: '',
    type: 'registry:component',
    files: [{
      path: 'src/registry/StickerCop/StickerCop.tsx',
      type: 'registry:component',
    }],
  },
  'sticker-animation-demo': {
    name: 'sticker-animation-demo',
    description: '',
    type: 'registry:example',
    files: [{
      path: 'src/registry/examples/sticker-animation-demo.tsx',
      type: 'registry:example',
    }],
    component: React.lazy(() => import('@/registry/examples/sticker-animation-demo.tsx')),
  },
  'navigation-menu': {
    name: 'navigation-menu',
    description: '',
    type: 'registry:component',
    files: [{
      path: 'src/registry/MainNavigation/MainNavigation.tsx',
      type: 'registry:component',
    }],
  },
  'navigation-menu-ssr-demo': {
    name: 'navigation-menu-ssr-demo',
    description: '',
    type: 'registry:example',
    files: [{
      path: 'src/registry/examples/navigation-menu-ssr-demo.tsx',
      type: 'registry:example',
    }],
    component: React.lazy(() => import('@/registry/examples/navigation-menu-ssr-demo.tsx')),
  },
}
